# Paths
path=(
  /usr/local/opt/coreutils/libexec/gnubin
  $DOTFILES/bin
  /usr/local/bin
  /usr/{sbin,bin}
  /{sbin,bin}
  /Applications/Postgres.app/Contents/Versions/latest/bin
)

cdpath=(
  $HOME/{,code,Desktop,Downloads}
)

fpath=(
  $HOME/.zfunctions
  $fpath
)

# Ensure path arrays do not contain duplicates.
typeset -gU path cdpath fpath

# load pyenv if available
if command -v pyenv >/dev/null; then
  export PYENV_ROOT="$HOME/.pyenv"
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init --path)"
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi

# load rbenv if available
if command -v rbenv >/dev/null; then
  eval "$(rbenv init - --no-rehash)"
fi

# load nodenv if available
if command -v nodenv >/dev/null; then
  eval "$(nodenv init -)"
fi

# load jenv if available
if command -v pyenv >/dev/null; then
  export PATH="/usr/local/opt/openjdk/bin:$PATH"
  export PATH="$HOME/.jenv/bin:$PATH"
  eval "$(jenv init -)"
fi
