# Paths
path=(
  /usr/local/opt/coreutils/libexec/gnubin
  $DOTFILES/bin
  /usr/local/bin
  /usr/{sbin,bin}
  /{sbin,bin}
  /Applications/Postgres.app/Contents/Versions/latest/bin
)

cdpath=(
  $HOME/{,code,Desktop,Downloads}
)

fpath=(
  $HOME/.zfunctions
  $fpath
)

# Ensure path arrays do not contain duplicates.
typeset -gU path cdpath fpath
