# Paths
path=(
  /opt/homebrew/opt/coreutils/libexec/gnubin
  $DOTFILES/bin
  /opt/homebrew/bin
  /usr/{sbin,bin}
  /{sbin,bin}
  /Applications/Postgres.app/Contents/Versions/latest/bin
)

cdpath=(
  $HOME/{,code,Desktop,Downloads}
)

fpath=(
  $HOME/.zfunctions
  $fpath
)

# Ensure path arrays do not contain duplicates.
typeset -gU path cdpath fpath

eval "$(/opt/homebrew/bin/brew shellenv)"
