# Enable a 256-color Terminal. This conditional statement ensures that the TERM
# variable is only set outside of tmux, since tmux sets its own terminal.
[[ -z "$TMUX" ]] && export TERM="xterm-256color"

# Use vim as the visual editor
# export VISUAL='nvim'
# export EDITOR=$VISUAL

# Reduce to 0.1 secs the delay after hitting the <ESC> key.
export KEYTIMEOUT=1

# The Curses based Pinentry needs a real tty device in order to work.
export GPG_TTY=$(tty)

DOTFILES="$HOME/.dotfiles"
SHELL="/usr/local/bin/zsh"
ZSH="$HOME/.zsh"
ZSH_MODULES_DIR="$DOTFILES/zsh/modules"

if [[ -z "$ZSH_CACHE_DIR" ]]; then
  ZSH_CACHE_DIR="$ZSH/cache"
fi

# According to https://github.com/Homebrew/brew/blob/master/docs/Analytics.md,
# Homebrew gathers anonymous aggregate user behaviour analytics and reporting
# these to Google Analytics. Opt out...
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_INSECURE_REDIRECT=1
export HOMEBREW_CASK_OPTS=--require-sha
